/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Noel Roberto
 */
public class VisualizarSimulacion extends javax.swing.JPanel {
    JTable tabla;
    String []colums;
    String[][]filas;
    DefaultTableModel tableListiner;

    /**
     * Creates new form VisualizarSimulacion
     */
    public VisualizarSimulacion() {
        cargarColumnas();
        initComponents();
        tableListiner=(DefaultTableModel)this.table.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(980, 589));

        table.setModel(new javax.swing.table.DefaultTableModel(
            filas,
            colums
        ));
        table.setMaximumSize(new java.awt.Dimension(968, 525));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Estadisticas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Simular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(114, 114, 114)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reporte pantalla = new Reporte();
               pantalla.setSize(980, 589);
                pantalla.setLocation(0, 0);
                removeAll();
                add(pantalla,BorderLayout.CENTER);
                revalidate();
                repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DecisionArchivo pantalla = new DecisionArchivo();
               pantalla.setSize(980, 589);
                pantalla.setLocation(0, 0);
                removeAll();
                add(pantalla,BorderLayout.CENTER);
                revalidate();
                repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tableListiner.getRowCount()!=0) {
            for (int i = tableListiner.getRowCount()-1; i >= 0; i--) {
                tableListiner.removeRow(i);
            }
            Inicio.renglones.clear();
            DecisionArchivo.simular();
            
        }
        
        int cantidad=0;
        for (Renglon renglone : Inicio.renglones) {
            String []fil = new String[11+(2*Inicio.nServs)];
            int i=0;
            fil[i]=renglone.getNum().toString();
            i++;
            fil[i]=Character.toString(renglone.getTipo());
            i++;
            fil[i]=renglone.getCliente().toString();
            i++;
            fil[i]=renglone.gettM().toString();
            for (int k = 0; k < Inicio.nServs; k++) {
                i++;
                fil[i]=renglone.getSSPosi(k).toString();
            }
            i++;
            fil[i]=renglone.getwL().toString();
            i++;
            fil[i]=renglone.getcSistema().toString();
            i++;
            fil[i]=renglone.getaT().toString();
            for (int k = 0; k < Inicio.nServs; k++) {
                i++;
                fil[i]=renglone.getDTPosi(k).toString();
            }
            i++;
            fil[i]=renglone.getnAleatorioTELL().toString();
            i++;
            fil[i]=renglone.getTiempoTELL().toString();
            i++;
            fil[i]=renglone.getnAleatorioTS().toString();
            i++;
            fil[i]=renglone.gettServicio().toString();
            tableListiner.addRow(fil);
            
            cantidad++;
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    public void cargarColumnas(){
       List<String> lista = new ArrayList<String>();
       lista.add("NEvento");
       lista.add("Tipo");
       lista.add("N Cliente");
       lista.add("TM");
        for (int i = 0; i < Inicio.nServs; i++) {
            lista.add("SS"+(i+1));
        }
        lista.add("WL");
        lista.add("Cl Sistema");
        lista.add("AT");
        for (int i = 0; i < Inicio.nServs; i++) {
            lista.add("DT"+(i+1));
        }
        lista.add("N. Aletorio Tell");
        lista.add("TELL");
        lista.add("N. Aleatorio TS");
        lista.add("TS");
        int tamaño=11+(Inicio.nServs*2);
        colums= new String[tamaño];
        int i=0;
        for(String e:lista){
            colums[i]=e;
            i++;
        }
    }
    public void cargarFilas(){
        int tamaño1=11+(Inicio.nServs*2);
        int cantidad=Inicio.renglones.size();
        if (cantidad>20) {
            cantidad=20;
        }
        filas=new String[20][tamaño1];
        int j=0;
        for (Renglon renglon : Inicio.renglones) {
            int i=0;
            filas[j][i]=renglon.getNum().toString();
            i++;
            filas[j][i]=Character.toString(renglon.getTipo());
            i++;
            filas[j][i]=renglon.getCliente().toString();
            i++;
            filas[j][i]=renglon.gettM().toString();
            for (int k = 0; k < Inicio.nServs; k++) {
                i++;
                filas[j][i]=renglon.getSSPosi(k).toString();
            }
            i++;
            filas[j][i]=renglon.getwL().toString();
            i++;
            filas[j][i]=renglon.getcSistema().toString();
            i++;
            filas[j][i]=renglon.getaT().toString();
            for (int k = 0; k < Inicio.nServs; k++) {
                i++;
                filas[j][i]=renglon.getDTPosi(k).toString();
            }
            i++;
            filas[j][i]=renglon.getnAleatorioTELL().toString();
            i++;
            filas[j][i]=renglon.getTiempoTELL().toString();
            i++;
            filas[j][i]=renglon.getnAleatorioTS().toString();
            i++;
            filas[j][i]=renglon.gettServicio().toString();
            if(j==20){
                return;
            }
            j++;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
